import 'package:modular_erp/core/security/app_permission.dart';
import 'package:modular_erp/core/security/permission_catalog.dart';
import 'package:modular_erp/core/security/permission_definition.dart';
import 'package:modular_erp/core/security/permission_scope.dart';

/// HR module permission contribution. Keys are stable and namespaced; scopes map
/// to the existing runtime [AppPermission] values.
const hrPermissionModules = <PermissionModule>[
  PermissionModule(
    id: 'hr',
    nameKey: 'hrPermModuleHr',
    order: 10,
    submodules: [
      PermissionSubmodule(
        id: 'employees',
        nameKey: 'hrPermSubEmployees',
        order: 1,
        definitions: [
          PermissionDefinition(
            key: 'hr.employees.view',
            moduleId: 'hr',
            submoduleId: 'employees',
            nameKey: 'hrPermEmployeesView',
            descriptionKey: 'hrPermEmployeesViewDesc',
            order: 1,
            permissions: {
              PermissionScope.self: AppPermission.employeeViewSelf,
              PermissionScope.team: AppPermission.employeeViewTeam,
              PermissionScope.all: AppPermission.employeeViewAll,
            },
          ),
          PermissionDefinition(
            key: 'hr.employees.create',
            moduleId: 'hr',
            submoduleId: 'employees',
            nameKey: 'hrPermEmployeesCreate',
            descriptionKey: 'hrPermEmployeesCreateDesc',
            order: 2,
            permissions: {PermissionScope.none: AppPermission.employeeCreate},
          ),
          PermissionDefinition(
            key: 'hr.employees.edit',
            moduleId: 'hr',
            submoduleId: 'employees',
            nameKey: 'hrPermEmployeesEdit',
            descriptionKey: 'hrPermEmployeesEditDesc',
            order: 3,
            permissions: {PermissionScope.none: AppPermission.employeeUpdate},
          ),
          PermissionDefinition(
            key: 'hr.employees.deactivate',
            moduleId: 'hr',
            submoduleId: 'employees',
            nameKey: 'hrPermEmployeesDeactivate',
            descriptionKey: 'hrPermEmployeesDeactivateDesc',
            order: 4,
            permissions: {
              PermissionScope.none: AppPermission.employeeDeactivate,
            },
          ),
        ],
      ),
      PermissionSubmodule(
        id: 'attendance',
        nameKey: 'hrPermSubAttendance',
        order: 2,
        definitions: [
          PermissionDefinition(
            key: 'hr.attendance.self.view',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceSelfView',
            descriptionKey: 'hrPermAttendanceSelfViewDesc',
            order: 1,
            requiresEmployeeLink: true,
            permissions: {
              PermissionScope.none: AppPermission.attendanceViewSelf,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.self.punch',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceSelfPunch',
            descriptionKey: 'hrPermAttendanceSelfPunchDesc',
            order: 2,
            requiresEmployeeLink: true,
            permissions: {
              PermissionScope.none: AppPermission.attendancePunchIn,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.self.punchOut',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceSelfPunchOut',
            descriptionKey: 'hrPermAttendanceSelfPunchOutDesc',
            order: 3,
            requiresEmployeeLink: true,
            permissions: {
              PermissionScope.none: AppPermission.attendancePunchOut,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.self.break',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceSelfBreak',
            descriptionKey: 'hrPermAttendanceSelfBreakDesc',
            order: 4,
            requiresEmployeeLink: true,
            permissions: {PermissionScope.none: AppPermission.attendanceBreak},
          ),
          PermissionDefinition(
            key: 'hr.attendance.self.correctionRequest',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceSelfCorrection',
            descriptionKey: 'hrPermAttendanceSelfCorrectionDesc',
            order: 5,
            requiresEmployeeLink: true,
            permissions: {
              PermissionScope.none: AppPermission.attendanceRequestCorrection,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.records.view',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceRecordsView',
            descriptionKey: 'hrPermAttendanceRecordsViewDesc',
            order: 6,
            permissions: {
              PermissionScope.team: AppPermission.attendanceViewTeam,
              PermissionScope.all: AppPermission.attendanceViewAll,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.corrections.review',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceCorrectionsReview',
            descriptionKey: 'hrPermAttendanceCorrectionsReviewDesc',
            order: 7,
            permissions: {
              PermissionScope.none: AppPermission.attendanceApprove,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.corrections.apply',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceCorrectionsApply',
            descriptionKey: 'hrPermAttendanceCorrectionsApplyDesc',
            order: 8,
            permissions: {
              PermissionScope.none: AppPermission.attendanceCorrect,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.reports.view',
            moduleId: 'hr',
            submoduleId: 'attendance',
            nameKey: 'hrPermAttendanceReportsView',
            descriptionKey: 'hrPermAttendanceReportsViewDesc',
            order: 9,
            permissions: {
              PermissionScope.none: AppPermission.attendanceReportView,
            },
          ),
        ],
      ),
      PermissionSubmodule(
        id: 'leave',
        nameKey: 'hrPermSubLeave',
        order: 3,
        definitions: [
          PermissionDefinition(
            key: 'hr.leave.self.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveSelfView',
            descriptionKey: 'hrPermLeaveSelfViewDesc',
            order: 1,
            requiresEmployeeLink: true,
            permissions: {PermissionScope.none: AppPermission.leaveViewSelf},
          ),
          PermissionDefinition(
            key: 'hr.leave.self.request',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveSelfRequest',
            descriptionKey: 'hrPermLeaveSelfRequestDesc',
            order: 2,
            requiresEmployeeLink: true,
            permissions: {PermissionScope.none: AppPermission.leaveRequest},
          ),
          PermissionDefinition(
            key: 'hr.leave.self.cancel',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveSelfCancel',
            descriptionKey: 'hrPermLeaveSelfCancelDesc',
            order: 3,
            requiresEmployeeLink: true,
            permissions: {PermissionScope.none: AppPermission.leaveCancelSelf},
          ),
          PermissionDefinition(
            key: 'hr.leave.self.balanceView',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveSelfBalance',
            descriptionKey: 'hrPermLeaveSelfBalanceDesc',
            order: 4,
            requiresEmployeeLink: true,
            permissions: {
              PermissionScope.none: AppPermission.leaveBalanceViewSelf,
            },
          ),
          PermissionDefinition(
            key: 'hr.leave.records.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveRecordsView',
            descriptionKey: 'hrPermLeaveRecordsViewDesc',
            order: 5,
            permissions: {
              PermissionScope.team: AppPermission.leaveViewTeam,
              PermissionScope.all: AppPermission.leaveViewAll,
            },
          ),
          PermissionDefinition(
            key: 'hr.leave.requests.review',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveRequestsReview',
            descriptionKey: 'hrPermLeaveRequestsReviewDesc',
            order: 6,
            permissions: {
              PermissionScope.team: AppPermission.leaveApproveTeam,
              PermissionScope.all: AppPermission.leaveApproveAll,
            },
          ),
          PermissionDefinition(
            key: 'hr.leave.balances.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveBalancesView',
            descriptionKey: 'hrPermLeaveBalancesViewDesc',
            order: 7,
            permissions: {
              PermissionScope.team: AppPermission.leaveBalanceViewTeam,
              PermissionScope.all: AppPermission.leaveBalanceViewAll,
            },
          ),
          PermissionDefinition(
            key: 'hr.leave.balances.adjust',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveBalancesAdjust',
            descriptionKey: 'hrPermLeaveBalancesAdjustDesc',
            order: 8,
            risk: PermissionRisk.elevated,
            permissions: {
              PermissionScope.none: AppPermission.leaveBalanceAdjust,
            },
          ),
          PermissionDefinition(
            key: 'hr.leave.settings.manage',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveSettingsManage',
            descriptionKey: 'hrPermLeaveSettingsManageDesc',
            order: 9,
            permissions: {PermissionScope.none: AppPermission.leaveManage},
          ),
          PermissionDefinition(
            key: 'hr.leave.types.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveTypesView',
            descriptionKey: 'hrPermLeaveTypesViewDesc',
            order: 10,
            permissions: {PermissionScope.none: AppPermission.leaveTypeView},
          ),
          PermissionDefinition(
            key: 'hr.leave.types.manage',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeaveTypesManage',
            descriptionKey: 'hrPermLeaveTypesManageDesc',
            order: 11,
            permissions: {PermissionScope.none: AppPermission.leaveTypeManage},
          ),
          PermissionDefinition(
            key: 'hr.leave.policies.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeavePoliciesView',
            descriptionKey: 'hrPermLeavePoliciesViewDesc',
            order: 12,
            permissions: {PermissionScope.none: AppPermission.leavePolicyView},
          ),
          PermissionDefinition(
            key: 'hr.leave.policies.manage',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermLeavePoliciesManage',
            descriptionKey: 'hrPermLeavePoliciesManageDesc',
            order: 13,
            permissions: {
              PermissionScope.none: AppPermission.leavePolicyManage,
            },
          ),
          PermissionDefinition(
            key: 'hr.holidays.view',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermHolidaysView',
            descriptionKey: 'hrPermHolidaysViewDesc',
            order: 14,
            permissions: {PermissionScope.none: AppPermission.holidayView},
          ),
          PermissionDefinition(
            key: 'hr.holidays.manage',
            moduleId: 'hr',
            submoduleId: 'leave',
            nameKey: 'hrPermHolidaysManage',
            descriptionKey: 'hrPermHolidaysManageDesc',
            order: 15,
            permissions: {PermissionScope.none: AppPermission.holidayManage},
          ),
        ],
      ),
      PermissionSubmodule(
        id: 'reports',
        nameKey: 'hrPermSubReports',
        order: 4,
        definitions: [
          PermissionDefinition(
            key: 'hr.reports.leave.view',
            moduleId: 'hr',
            submoduleId: 'reports',
            nameKey: 'hrPermReportsLeaveView',
            descriptionKey: 'hrPermReportsLeaveViewDesc',
            order: 1,
            permissions: {PermissionScope.none: AppPermission.leaveReportView},
          ),
        ],
      ),
      PermissionSubmodule(
        id: 'configuration',
        nameKey: 'hrPermSubConfiguration',
        order: 5,
        definitions: [
          PermissionDefinition(
            key: 'hr.attendance.shifts.view',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermShiftsView',
            descriptionKey: 'hrPermShiftsViewDesc',
            order: 1,
            permissions: {PermissionScope.none: AppPermission.shiftView},
          ),
          PermissionDefinition(
            key: 'hr.attendance.shifts.manage',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermShiftsManage',
            descriptionKey: 'hrPermShiftsManageDesc',
            order: 2,
            permissions: {PermissionScope.none: AppPermission.shiftManage},
          ),
          PermissionDefinition(
            key: 'hr.attendance.locations.view',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermLocationsView',
            descriptionKey: 'hrPermLocationsViewDesc',
            order: 3,
            permissions: {PermissionScope.none: AppPermission.workLocationView},
          ),
          PermissionDefinition(
            key: 'hr.attendance.locations.manage',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermLocationsManage',
            descriptionKey: 'hrPermLocationsManageDesc',
            order: 4,
            permissions: {
              PermissionScope.none: AppPermission.workLocationManage,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.policies.view',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermPoliciesView',
            descriptionKey: 'hrPermPoliciesViewDesc',
            order: 5,
            permissions: {
              PermissionScope.none: AppPermission.attendancePolicyView,
            },
          ),
          PermissionDefinition(
            key: 'hr.attendance.policies.manage',
            moduleId: 'hr',
            submoduleId: 'configuration',
            featureFlag: 'settings',
            nameKey: 'hrPermPoliciesManage',
            descriptionKey: 'hrPermPoliciesManageDesc',
            order: 6,
            permissions: {
              PermissionScope.none: AppPermission.attendancePolicyManage,
            },
          ),
        ],
      ),
    ],
  ),
];
