import 'package:modular_erp/l10n/l10n.dart';

/// Resolves catalog localization keys to generated ARB getters. The Access UI
/// composes these so administrators see friendly labels, never permission keys.
extension AccessCatalogLocalization on AppLocalizations {
  String moduleLabel(String key) => switch (key) {
    'hr' || 'hrPermModuleHr' => hrPermModuleHr,
    'services' || 'servicesPermModuleServices' => servicesPermModuleServices,
    'platform' || 'accessModulePlatform' => accessModulePlatform,
    _ => key,
  };

  String submoduleLabel(String key) => switch (key) {
    'employees' => hrPermSubEmployees,
    'attendance' => hrPermSubAttendance,
    'leave' => hrPermSubLeave,
    'reports' => hrPermSubReports,
    'configuration' => hrPermSubConfiguration,
    'access' => accessSubAccess,
    'customers' => servicesPermSubCustomers,
    'sites' => servicesPermSubSites,
    'teams' => servicesPermSubTeams,
    _ => key,
  };

  String permissionLabel(String key) => switch (key) {
    'hrPermEmployeesView' => hrPermEmployeesView,
    'hrPermEmployeesCreate' => hrPermEmployeesCreate,
    'hrPermEmployeesEdit' => hrPermEmployeesEdit,
    'hrPermEmployeesDeactivate' => hrPermEmployeesDeactivate,
    'hrPermAttendanceSelfView' => hrPermAttendanceSelfView,
    'hrPermAttendanceSelfPunch' => hrPermAttendanceSelfPunch,
    'hrPermAttendanceSelfPunchOut' => hrPermAttendanceSelfPunchOut,
    'hrPermAttendanceSelfBreak' => hrPermAttendanceSelfBreak,
    'hrPermAttendanceSelfCorrection' => hrPermAttendanceSelfCorrection,
    'hrPermAttendanceRecordsView' => hrPermAttendanceRecordsView,
    'hrPermAttendanceCorrectionsReview' => hrPermAttendanceCorrectionsReview,
    'hrPermAttendanceCorrectionsApply' => hrPermAttendanceCorrectionsApply,
    'hrPermAttendanceReportsView' => hrPermAttendanceReportsView,
    'hrPermLeaveSelfView' => hrPermLeaveSelfView,
    'hrPermLeaveSelfRequest' => hrPermLeaveSelfRequest,
    'hrPermLeaveSelfCancel' => hrPermLeaveSelfCancel,
    'hrPermLeaveSelfBalance' => hrPermLeaveSelfBalance,
    'hrPermLeaveRecordsView' => hrPermLeaveRecordsView,
    'hrPermLeaveRequestsReview' => hrPermLeaveRequestsReview,
    'hrPermLeaveBalancesView' => hrPermLeaveBalancesView,
    'hrPermLeaveBalancesAdjust' => hrPermLeaveBalancesAdjust,
    'hrPermLeaveSettingsManage' => hrPermLeaveSettingsManage,
    'hrPermLeaveTypesView' => hrPermLeaveTypesView,
    'hrPermLeaveTypesManage' => hrPermLeaveTypesManage,
    'hrPermLeavePoliciesView' => hrPermLeavePoliciesView,
    'hrPermLeavePoliciesManage' => hrPermLeavePoliciesManage,
    'hrPermHolidaysView' => hrPermHolidaysView,
    'hrPermHolidaysManage' => hrPermHolidaysManage,
    'hrPermReportsLeaveView' => hrPermReportsLeaveView,
    'hrPermShiftsView' => hrPermShiftsView,
    'hrPermShiftsManage' => hrPermShiftsManage,
    'hrPermLocationsView' => hrPermLocationsView,
    'hrPermLocationsManage' => hrPermLocationsManage,
    'hrPermPoliciesView' => hrPermPoliciesView,
    'hrPermPoliciesManage' => hrPermPoliciesManage,
    'accessUsersView' => accessUsersView,
    'accessPermissionsManage' => accessPermissionsManage,
    'accessModulesView' => accessModulesView,
    'accessCompanyUsersManage' => accessCompanyUsersManage,
    'accessPlatformCompaniesManage' => accessPlatformCompaniesManage,
    'accessPlatformModulesManage' => accessPlatformModulesManage,
    'servicesPermCustomersView' => servicesPermCustomersView,
    'servicesPermCustomersCreate' => servicesPermCustomersCreate,
    'servicesPermCustomersEdit' => servicesPermCustomersEdit,
    'servicesPermCustomersDeactivate' => servicesPermCustomersDeactivate,
    'servicesPermSitesView' => servicesPermSitesView,
    'servicesPermSitesCreate' => servicesPermSitesCreate,
    'servicesPermSitesEdit' => servicesPermSitesEdit,
    'servicesPermSitesDeactivate' => servicesPermSitesDeactivate,
    'servicesPermTeamsView' => servicesPermTeamsView,
    'servicesPermTeamsManage' => servicesPermTeamsManage,
    'servicesPermServiceTypesView' => servicesPermServiceTypesView,
    'servicesPermServiceTypesManage' => servicesPermServiceTypesManage,
    'servicesPermComplaintTypesView' => servicesPermComplaintTypesView,
    'servicesPermComplaintTypesManage' => servicesPermComplaintTypesManage,
    'servicesPermPrioritiesView' => servicesPermPrioritiesView,
    'servicesPermPrioritiesManage' => servicesPermPrioritiesManage,
    'servicesPermTicketTypesView' => servicesPermTicketTypesView,
    'servicesPermTicketTypesManage' => servicesPermTicketTypesManage,
    _ => key,
  };

  String permissionDescription(String key) => switch (key) {
    'hrPermEmployeesViewDesc' => hrPermEmployeesViewDesc,
    'hrPermEmployeesCreateDesc' => hrPermEmployeesCreateDesc,
    'hrPermEmployeesEditDesc' => hrPermEmployeesEditDesc,
    'hrPermEmployeesDeactivateDesc' => hrPermEmployeesDeactivateDesc,
    'hrPermAttendanceSelfViewDesc' => hrPermAttendanceSelfViewDesc,
    'hrPermAttendanceSelfPunchDesc' => hrPermAttendanceSelfPunchDesc,
    'hrPermAttendanceSelfPunchOutDesc' => hrPermAttendanceSelfPunchOutDesc,
    'hrPermAttendanceSelfBreakDesc' => hrPermAttendanceSelfBreakDesc,
    'hrPermAttendanceSelfCorrectionDesc' => hrPermAttendanceSelfCorrectionDesc,
    'hrPermAttendanceRecordsViewDesc' => hrPermAttendanceRecordsViewDesc,
    'hrPermAttendanceCorrectionsReviewDesc' =>
      hrPermAttendanceCorrectionsReviewDesc,
    'hrPermAttendanceCorrectionsApplyDesc' =>
      hrPermAttendanceCorrectionsApplyDesc,
    'hrPermAttendanceReportsViewDesc' => hrPermAttendanceReportsViewDesc,
    'hrPermLeaveSelfViewDesc' => hrPermLeaveSelfViewDesc,
    'hrPermLeaveSelfRequestDesc' => hrPermLeaveSelfRequestDesc,
    'hrPermLeaveSelfCancelDesc' => hrPermLeaveSelfCancelDesc,
    'hrPermLeaveSelfBalanceDesc' => hrPermLeaveSelfBalanceDesc,
    'hrPermLeaveRecordsViewDesc' => hrPermLeaveRecordsViewDesc,
    'hrPermLeaveRequestsReviewDesc' => hrPermLeaveRequestsReviewDesc,
    'hrPermLeaveBalancesViewDesc' => hrPermLeaveBalancesViewDesc,
    'hrPermLeaveBalancesAdjustDesc' => hrPermLeaveBalancesAdjustDesc,
    'hrPermLeaveSettingsManageDesc' => hrPermLeaveSettingsManageDesc,
    'hrPermLeaveTypesViewDesc' => hrPermLeaveTypesViewDesc,
    'hrPermLeaveTypesManageDesc' => hrPermLeaveTypesManageDesc,
    'hrPermLeavePoliciesViewDesc' => hrPermLeavePoliciesViewDesc,
    'hrPermLeavePoliciesManageDesc' => hrPermLeavePoliciesManageDesc,
    'hrPermHolidaysViewDesc' => hrPermHolidaysViewDesc,
    'hrPermHolidaysManageDesc' => hrPermHolidaysManageDesc,
    'hrPermReportsLeaveViewDesc' => hrPermReportsLeaveViewDesc,
    'hrPermShiftsViewDesc' => hrPermShiftsViewDesc,
    'hrPermShiftsManageDesc' => hrPermShiftsManageDesc,
    'hrPermLocationsViewDesc' => hrPermLocationsViewDesc,
    'hrPermLocationsManageDesc' => hrPermLocationsManageDesc,
    'hrPermPoliciesViewDesc' => hrPermPoliciesViewDesc,
    'hrPermPoliciesManageDesc' => hrPermPoliciesManageDesc,
    'accessUsersViewDesc' => accessUsersViewDesc,
    'accessPermissionsManageDesc' => accessPermissionsManageDesc,
    'accessModulesViewDesc' => accessModulesViewDesc,
    'accessCompanyUsersManageDesc' => accessCompanyUsersManageDesc,
    'accessPlatformCompaniesManageDesc' => accessPlatformCompaniesManageDesc,
    'accessPlatformModulesManageDesc' => accessPlatformModulesManageDesc,
    'servicesPermCustomersViewDesc' => servicesPermCustomersViewDesc,
    'servicesPermCustomersCreateDesc' => servicesPermCustomersCreateDesc,
    'servicesPermCustomersEditDesc' => servicesPermCustomersEditDesc,
    'servicesPermCustomersDeactivateDesc' =>
      servicesPermCustomersDeactivateDesc,
    'servicesPermSitesViewDesc' => servicesPermSitesViewDesc,
    'servicesPermSitesCreateDesc' => servicesPermSitesCreateDesc,
    'servicesPermSitesEditDesc' => servicesPermSitesEditDesc,
    'servicesPermSitesDeactivateDesc' => servicesPermSitesDeactivateDesc,
    'servicesPermTeamsViewDesc' => servicesPermTeamsViewDesc,
    'servicesPermTeamsManageDesc' => servicesPermTeamsManageDesc,
    'servicesPermServiceTypesViewDesc' => servicesPermServiceTypesViewDesc,
    'servicesPermServiceTypesManageDesc' => servicesPermServiceTypesManageDesc,
    'servicesPermComplaintTypesViewDesc' => servicesPermComplaintTypesViewDesc,
    'servicesPermComplaintTypesManageDesc' =>
      servicesPermComplaintTypesManageDesc,
    'servicesPermPrioritiesViewDesc' => servicesPermPrioritiesViewDesc,
    'servicesPermPrioritiesManageDesc' => servicesPermPrioritiesManageDesc,
    'servicesPermTicketTypesViewDesc' => servicesPermTicketTypesViewDesc,
    'servicesPermTicketTypesManageDesc' => servicesPermTicketTypesManageDesc,
    _ => key,
  };

  String scopeLabel(String scope) => switch (scope) {
    'none' => accessScopeNone,
    'self' => accessScopeSelf,
    'assigned' => accessScopeAssigned,
    'team' => accessScopeTeam,
    'all' => accessScopeAll,
    _ => scope,
  };
}
